name: Pack LeviLamina With BDS[Auto]

on:
  schedule:
    - cron: '0 16 * * *' 
  workflow_dispatch:
  
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Check Out
      uses: actions/checkout@v3
    - name: Get Latest Release
      id: latest_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: LiteLDev
        repo: LeviLamina
    - name: Remove 'v' from version
      id: format_version
      run: echo "::set-output name=version::$(echo ${{ steps.latest_version.outputs.release }} | cut -c 2-)"
    - name: Install Lip
      run: |
        rm README.md
        rm LICENSE
        Invoke-WebRequest -Uri https://github.com/lippkg/lip/releases/download/v0.21.2/lip-windows-amd64.zip -Outfile ./lip.zip
        unzip lip.zip
    - name: Install LeviLamina
      run: |
        mkdir llbds
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LeviLamina@${{ steps.format_version.outputs.version }}
        ls
    - name: Install LSE
      run: |
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LegacyScriptEngine
        cd ../
    - name: Get BDS core version and delete file
      id: get_bds_core_version
      run: |
        $file = Get-ChildItem -Path .\llbds\.cache\bdsdown\ -File | Select-Object -First 1
        echo "::set-output name=bds_core_version::$(echo $file.Name)"
        Remove-Item -Path $file.FullName
    - name: Pack files
      run: |
        Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2401-x64.exe -Outfile ./7z.exe
        .\7z.exe
        7z a -tzip llbds.zip llbds\
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: llbds.zip 
        name: LeviLaminaBDS - ${{ steps.format_version.outputs.version  }}
        tag_name: ${{ steps.format_version.outputs.version  }}
        body: |
          LeviLamina version: ${{ steps.format_version.outputs.version  }}
          Support BDS core: ${{ steps.get_bds_core_version.outputs.bds_core_version }}
          Include LSE: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
