name: Pack LeviLamina

on:
  workflow_dispatch:
    inputs:
      LL_VER:
        description: 'LeviLamina version'
        required: true
        default: '0.1.0'
      LSE:
        description: 'If include LegacyScriptEngine'
        required: false
        default: 'false'
      RUNTIME:
        description: 'If include runtime for LeviLamina'
        required: false
        default: 'false'
      SCRIPTS:
        description: 'Use user_scripts.bat'
        required: false
        default: 'false'

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    
    - name: ðŸ’¡ Check Out Repo
      uses: actions/checkout@v3

    - name: ðŸ› ï¸ Install Lip & Prepare Environment
      run: |
        rm README.md
        mkdir ll
        mv .\LICENSE .\ll\LICENSE
        Invoke-WebRequest -Uri https://github.com/lippkg/lip/releases/latest/download/lip-windows-amd64.zip -Outfile .\lip.zip
        Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2401-x64.exe -Outfile .\7z.exe
        .\7z.exe
        unzip lip.zip
        "$env:GITHUB_WORKSPACE" | Out-File -FilePath $env:GITHUB_PATH -Append


    - name: ðŸ§° Install LeviLamina
      run: |
        cd ll
        lip install -y github.com/LiteLDev/LeviLamina@${{ github.event.inputs.LL_VER }}
    
    - name: âš™ï¸ Install LSE
      if: github.event.inputs.LSE == 'true'
      run: |
        cd ll
        lip.exe install -y github.com/LiteLDev/LegacyScriptEngine
        lip.exe install -y gitea.litebds.com/LiteLDev/legacy-script-engine-nodejs
        lip.exe install -y gitea.litebds.com/LiteLDev/legacy-script-engine-python
        cd ..\
    
    - name: ðŸ”§ Install Runtime
      if: github.event.inputs.RUNTIME == 'true'
      run: |
        cd ll
        Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vc_redist.x64.exe -Outfile .\runtime_for_levilamina.exe
        cd ..\
    
    - name: ðŸ“œ Run User's Scripts
      if: github.event.inputs.SCRIPTS == 'true'
      run: |
        cd ll
        # alias ..\lip.exe install -y -> lipin
        user_scripts.bat
        cd ..\
    
    - name: ðŸ“‚ Get BDS Core Version & Remove BDS
      id: get_bds_core_version
      run: |
        $file = Get-ChildItem -Path .\ll\.cache\bdsdown\ -File | Select-Object -First 1
        echo "name=bds_core_version::$(echo $file.Name)" >> $GITHUB_OUTPUT
        Remove-Item -Path $file.FullName
        cd ll
        ls
        rm .\behavior_packs -Force -Recurse
        rm .\definitions -Force -Recurse
        rm .\resource_packs -Force -Recurse
        rm .\bedrock_* -Force -Recurse
        rm .\config -Force -Recurse
        rm .\.cache -Force -Recurse
        rm .\allowlist.json -Force
        rm .\bdsdown.exe -Force
        rm .\permissions.json -Force
        rm .\release-notes.txt -Force
        rm .\server.properties -Force
        cd ..\
    
    - name: ðŸ“¦ Pack Files
      run: |
        7z a -tzip ll_${{ github.event.inputs.LL_VER  }}_${{ steps.get_bds_core_version.outputs.bds_core_version }} ll\
    
    - name: ðŸŽ‰ Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: ll_${{ github.event.inputs.LL_VER  }}_${{ steps.get_bds_core_version.outputs.bds_core_version }} 
        name: LeviLamina packed - ${{ github.event.inputs.LL_VER  }}
        tag_name: ${{ github.event.inputs.LL_VER  }}
        body: |
          LeviLamina version: ${{ github.event.inputs.LL_VER  }}
          BDS core needed version: ${{ steps.get_bds_core_version.outputs.bds_core_version }}
          Include LSE: ${{ github.event.inputs.LSE }}
          Include Runtime: ${{ github.event.inputs.RUNTIME }}
          Use user'_scripts.bat: ${{ github.event.inputs.SCRIPTS }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
